# Naive Bayes classifier

Implementing a simpler Naive Bayes classifier for email spam classification in Python.
Naive Bayes is a machine learning algorithm commonly used for classification problems.

Essentially, it predicts the probabilities of different classes based on the features of the data.


The Naive Bayes classifier is based on the principles of Bayes' theorem. This theorem relates the probability of an event to the conditions under which the event occurs and the available data. The Naive Bayes classifier offers a simple computation method by making assumptions.


The "naive" name of the Naive Bayes classifier stems from the assumption that each feature is independent of the others. It disregards relationships between features and treats each feature independently. This assumption simplifies the computations and speeds up the classification process.


The Naive Bayes classifier calculates the probabilities of features in the dataset. Then, based on the features of a new instance, it predicts the probability values for the class label. The predictions are typically made using the maximum likelihood principle, selecting the class with the highest probability.


In this way, the Naive Bayes classifier can be effectively used in classification problems, particularly in areas such as text classification, spam filtering, and sentiment analysis.

In [5]:
import numpy as np

In [6]:
X_train = np.array([[1,0,1,0],[0,1,1,1],[1,1,0,0],[0,0,1,1]]  )


we can consider the following as a possible fourth feature:

Email: Contains the word "advertisement", Email length > 100, Sender unknown, Attached file present

Email: Does not contain the word "advertisement", Email length < 50, Sender known, No attached file

Email: Contains the word "advertisement", Email length > 100, Sender known, No attached file

Email: Does not contain the word "advertisement", Email length < 50, Sender unknown, Attached file present

In [7]:
y_train=np.array([1,0,1,0])

In [14]:
X_test = np.array([[1, 0, 1, 1], [0, 1, 0, 1]])


y_train=np.array([1,0,1,0]) represents the classes of the emails in the training dataset. Here, the labels indicating the class of each email are represented as a NumPy array.

Each element of the array corresponds to the classes of the emails in the training dataset, respectively. For example:

The first email is labeled as spam (class 1).

The second email is labeled as not spam (class 0).

The third email is labeled as spam (class 1).

The fourth email is labeled as not spam (class 0).

In this way, the correct class labels for each email are stored in the y_train array. These labels are used to classify the emails in the training dataset as spam or not spam.

In [8]:
classes = np.unique(y_train)
num_classes = len(classes)

In [9]:
classes

array([0, 1])

classes = np.unique(y_train) and num_classes = len(classes) is used to determine the unique classes present in the training labels (y_train) and calculate the number of unique classes.

Here is an explanation of each line:

classes = np.unique(y_train): This line uses the np.unique() function from the NumPy library to find the unique elements in the y_train array. It returns an array (classes) containing the unique classes present in y_train.
The unique function removes duplicate elements and sorts the array in ascending order.

num_classes = len(classes): This line calculates the number of unique classes by using the len() function to get the length of the classes array. The length of an array represents the number of elements in it, so num_classes will store the count of unique classes.



In [10]:
class_priors = np.zeros(num_classes)
for i, cls in enumerate(classes):
    class_priors[i] = np.sum(y_train == cls) / len(y_train)

class_priors = np.zeros(num_classes): This line initializes an array class_priors with zeros, with a length equal to the number of unique classes (num_classes). This array will store the class priors.

for i, cls in enumerate(classes):: This line starts a loop that iterates over each unique class in the classes array. It uses the enumerate() function to iterate over both the index (i) and the value (cls) of each element in classes.

class_priors[i] = np.sum(y_train == cls) / len(y_train): Inside the loop, this line calculates the class prior probability for the current class (cls). It does so by counting the occurrences of the current class in the y_train array using the expression np.sum(y_train == cls). This counts the number of elements in y_train that are equal to the current class. Then, it divides this count by the total number of training samples (len(y_train)) to obtain the class prior probability. The calculated probability is then assigned to the corresponding index i in the class_priors array.

After executing these lines, the class_priors array will contain the calculated class prior probabilities for each unique class in the training data. These probabilities indicate the likelihood of encountering each class in the dataset and can be used as a prior belief in classification tasks.

class_priors[i]. Prior belief

In [11]:
num_features = X_train.shape[1]
feature_likelihoods = np.zeros((num_classes, num_features))

num_features = X_train.shape[1]: This line retrieves the number of features in the training data (X_train). The shape attribute of a NumPy array returns a tuple representing the dimensions of the array. Since X_train is a 2-dimensional array, the shape is given as (num_samples, num_features). By accessing the second element of the shape tuple (X_train.shape[1]), we get the number of features in the dataset, which is stored in the variable num_features.

feature_likelihoods = np.zeros((num_classes, num_features)): This line initializes an array feature_likelihoods with zeros. The shape of this array is (num_classes, num_features), where num_classes is the number of unique classes and num_features is the number of features in the training data. This array will store the calculated likelihood probabilities for each feature in each class.

After executing these lines, the variable num_features will hold the count of features, and the feature_likelihoods array will be initialized with zeros and ready to store the likelihood probabilities for each feature in each class.

In [12]:
for i, cls in enumerate(classes):
    X_class = X_train[y_train == cls]
    feature_likelihoods[i] = np.mean(X_class, axis=0)

for i, cls in enumerate(classes):: This line initiates a loop that iterates over each unique class in the classes array. The enumerate() function is used to iterate over both the index (i) and the value (cls) of each element in classes.

X_class = X_train[y_train == cls]: Inside the loop, this line creates a subset of the training data X_train for the current class (cls). It uses boolean indexing to select rows from X_train where the corresponding label in y_train is equal to the current class. This subset of rows is assigned to the variable X_class.

feature_likelihoods[i] = np.mean(X_class, axis=0): This line calculates the feature likelihood probabilities for the current class and assigns them to the corresponding row in the feature_likelihoods array.

np.mean(X_class, axis=0) calculates the mean value of each column (feature) in the X_class array. The axis=0 parameter specifies that the mean should be taken along the columns.

The resulting mean values represent the likelihood probabilities for each feature in the current class. The calculated probabilities are then assigned to the corresponding row (i) in the feature_likelihoods array, which stores the likelihood probabilities for each feature in each class.

The loop repeats for each class, allowing the code to calculate the feature likelihood probabilities for all classes present in the training data.

# Explanation of the X_class

In [2]:
import numpy as np

X_train = np.array([[1, 0, 1, 0],   # 1. e-posta
                   [0, 1, 1, 1],   # 2. e-posta
                   [1, 1, 0, 0],   # 3. e-posta
                   [0, 0, 1, 1]])  # 4. e-posta
y_train = np.array([1, 0, 1, 0])

classes = np.unique(y_train)

for i, cls in enumerate(classes):
    X_class = X_train[y_train == cls]
    print(f"Class: {cls}")
    print(f"X_class:\n{X_class}")
    print("---------")

Class: 0
X_class:
[[0 1 1 1]
 [0 0 1 1]]
---------
Class: 1
X_class:
[[1 0 1 0]
 [1 1 0 0]]
---------


Yukarıdaki örnekte, X_train dizisinde dört e-posta bulunur ve her biri dört özelliği temsil eder. y_train dizisi, her e-postaya karşılık gelen sınıf etiketlerini içerir. Döngüde, enumerate(classes) kullanılarak sınıflar üzerinde dönülür. Her döngü adımında, cls değişkeni geçerli sınıf değerini alır.

İlk döngüde, cls değeri 0'dır. y_train == cls ifadesi, y_train dizisini 0 ile karşılaştırır ve bu koşulu sağlayan konumları temsil eden bir boolean maske oluşturur. Bu maske, 0'a karşılık gelen e-postaların bulunduğu satırları seçmek için X_train dizisine uygulanır. Sonuç olarak, X_class değişkeni, 0 sınıfına ait e-postaların özelliklerini içeren bir alt küme olarak atanır.

Aynı işlem, ikinci döngü adımında cls değeri 1 olduğunda da tekrarlanır. Bu sefer, y_train dizisindeki 1'lere karşılık gelen e-postaların özelliklerini temsil eden başka bir alt küme olan X_class değişkenine atanır.

Bu örnekte, X_class değişkeni, her bir sınıfa ait örneklerin özelliklerini içeren alt kümeleri temsil etmektedir.

X_train = np.array([[1, 0, 1, 0], # 1. e-posta
[0, 1, 1, 1], # 2. e-posta
[1, 1, 0, 0], # 3. e-posta
[0, 0, 1, 1]]) # 4. e-posta

y_train = np.array([1, 0, 1, 0])

Sınıflar (yani sınıf etiketleri) ise:

classes = np.unique(y_train) # [0, 1]

Şimdi, for döngüsü içinde her bir sınıf için ayrı ayrı işlemler yapılıyor.

İlk döngü adımında:

cls = 0

y_train == cls ifadesi, y_train dizisinde 0'ya eşit olan konumları belirleyen bir boolean maske oluşturur. Bu maske [False, True, False, True] şeklindedir.

Bu maskeyi X_train dizisine uyguladığımızda, yalnızca True değerlere karşılık gelen satırlar seçilir ve X_class değişkenine atanır. Bu durumda, [False, True, False, True] maskesi, 2. ve 4. satırları seçer ve X_class şu şekilde olur:

X_class:
[[0 1 1 1]
[0 0 1 1]]

Bu işlem, 0 sınıfına ait e-postaların özelliklerini içeren X_class alt kümesini elde etmemizi sağlar.

İkinci döngü adımında:

cls = 1

y_train == cls ifadesi, y_train dizisinde 1'e eşit olan konumları belirleyen bir boolean maske oluşturur. Bu maske [True, False, True, False] şeklindedir.

Bu maskeyi X_train dizisine uyguladığımızda, yalnızca True değerlere karşılık gelen satırlar seçilir ve X_class değişkenine atanır. Bu durumda, [True, False, True, False] maskesi, 1. ve 3. satırları seçer ve X_class şu şekilde olur:

X_class:
[[1 0 1 0]
[1 1 0 0]]

Bu işlem, 1 sınıfına ait e-postaların özelliklerini içeren X_class alt kümesini elde etmemizi sağlar.

Sonuç olarak, for döngüsü içindeki işlemler, her bir sınıfa ait e-postaların özelliklerini içeren X_class alt kümelerini oluşturur. Bu alt kümeler, sınıf etiketlerine göre gruplandırılmış özellik veriler

In [15]:
num_samples = X_test.shape[0]
predictions = np.zeros(num_samples, dtype=int)

In [16]:
for i in range(num_samples):
    posterior_probs = np.zeros(num_classes)
    for j, cls in enumerate(classes):
        prior = class_priors[j]
        likelihood = np.prod(feature_likelihoods[j] ** X_test[i] * (1 - feature_likelihoods[j]) ** (1 - X_test[i]))
        posterior_probs[j] = prior * likelihood

    predictions[i] = np.argmax(posterior_probs)

For each sample in the test data, calculate the posterior probabilities for each class. Multiply the class prior (prior) with the likelihoods of features (likelihood) given that class. 
Store the class with the highest probability in predictions.

In [17]:
for i, pred in enumerate(predictions):
    print("Sample", i+1, "predicted as:", "spam" if pred == 1 else "ham")

Sample 1 predicted as: ham
Sample 2 predicted as: ham
